# Generated by Django 4.1.2 on 2022-11-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=255)),
                ('pattern_description', models.TextField()),
                ('pattern_created_at', models.DateTimeField(auto_now_add=True)),
                ('pattern_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.resource')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.role')),
            ],
        ),
        migrations.CreateModel(
            name='PatternResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_available_time', models.IntegerField()),
                ('pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.pattern')),
                ('resource', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_position', models.IntegerField()),
                ('activity_time', models.IntegerField()),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.activity')),
                ('pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.pattern')),
            ],
        ),
    ]
